services:
  postgres:
    image: postgres:17
    container_name: postgres-ecom
    environment:
      POSTGRES_DB: ecomdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: