spring:
  application:
    name: ecom-application
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

server:
  shutdown: graceful

info:
  app:
    name: EcomApp
    description: App built for learning
    version: 1.0.0